### ISSUE TITLE
about qtermwidget

### ISSUE THREAD

**Issue by hongnod** [softengineer/qsshterm#1]
You mentioned ‘qtermwidget’ in the readme.md, can you pls give a dedicate link to the project?

thanks a lot.

**Comment by topillar** [comment]
no answer, close it then.

**Comment by softengineer** [comment]
Sorry for replying you late, I will add the link to Readme.md, the link is https://github.com/lxqt/qtermwidget, but i’d like to notice currently qtermwidget  only works on unix-like platform, to make it work on window, I changes some codes for that project. I will upload them after then.
