### ISSUE TITLE
Can you build  "3rdparty/qtermwidget/" successfully?

### ISSUE THREAD

**Issue by hongnod** [softengineer/qsshterm#3]
On windows, compile  qtermwidget as your guide. run cmake fine. but mingw-make reports error:<sys/ioctl.h> in kpty.cpp can't find.
Can you please instruct me how to correct it?

**Comment by softengineer** [comment]
which mingw-make do you use? If you install the latest version of qt5-mingw , there is ioctl.h in qt5 mingw include directory ( in my side, it's ...\Qt\5.10.1\mingw53_32\include\sys\ioctl.h),  to compile the project, the mingw32-make in qt5 should be used.

**Comment by hongnod** [comment]
I tried to install 5.9.6 5.10.1 5.11.1, all of them don't have ioctl.h.

**Comment by hongnod** [comment]
Comment out :
#include <sys/ioctl.h>
#include <sys/resource.h>
in kpty.cpp

and #include <sys/ioctl.h> in kptydevice.cpp

I can build  libqtermwidget5.dll.a & libqtermwidget5.dll successfully.

So I guess  some ifdef are needed.

**Comment by softengineer** [comment]
Yes, those two files are no needed in windows version of kptydevice.cpp, I will add ifdef in that file, thanks for reminder.
